chore: simplify Dockerfiles

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -218,62 +218,30 @@ jobs:
       - uses: actions/checkout@v4
       - uses: cashapp/activate-hermit@v1.1.3
       - run: go-arch-lint check || true
-  docker-build-controller:
-    name: Build Controller Docker Image
-    # if: github.event_name != 'pull_request' || github.event.action == 'enqueued' || contains( github.event.pull_request.labels.*.name, 'run-all')
+  docker-shard:
+    name: Shard Docker Builds
     runs-on: ubuntu-latest
+    outputs:
+      matrix: ${{ steps.set-matrix.outputs.matrix }}
+    steps:
+      - uses: actions/checkout@v4
+      - uses: cashapp/activate-hermit@v1.1.3
+      - id: set-matrix
+        run: echo "matrix=$(just list-docker-images | tr -d '\n' | jq -R -s -c 'split(" ")')" >> "$GITHUB_OUTPUT"
+  docker-build:
+    name: Build ${{ matrix.service }} Docker Image
+    needs: docker-shard
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        service: ${{ fromJson(needs.docker-shard.outputs.matrix) }}
     steps:
       - uses: actions/checkout@v4
       - uses: cashapp/activate-hermit@v1.1.3
       - uses: ./.github/actions/build-cache
-      - run: just build-docker controller
-  docker-build-provisioner:
-    name: Build Provisioner Docker Image
-    # if: github.event_name != 'pull_request' || github.event.action == 'enqueued' || contains( github.event.pull_request.labels.*.name, 'run-all')
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-      - uses: cashapp/activate-hermit@v1.1.3
-      - uses: ./.github/actions/build-cache
-      - run: just build-docker provisioner
-  docker-build-cron:
-    name: Build Cron Docker Image
-    # if: github.event_name != 'pull_request' || github.event.action == 'enqueued' || contains( github.event.pull_request.labels.*.name, 'run-all')
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-      - uses: cashapp/activate-hermit@v1.1.3
-      - uses: ./.github/actions/build-cache
-      - run: just build-docker cron
-  docker-build-http-ingress:
-    name: Build HTTP Ingress Docker Image
-    # if: github.event_name != 'pull_request' || github.event.action == 'enqueued' || contains( github.event.pull_request.labels.*.name, 'run-all')
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-      - uses: cashapp/activate-hermit@v1.1.3
-      - uses: ./.github/actions/build-cache
-      - run: just build-docker http-ingress
-  docker-build-runner:
-    name: Build Runner Docker Images
-    # if: github.event_name != 'pull_request' || github.event.action == 'enqueued' || contains( github.event.pull_request.labels.*.name, 'run-all')
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-      - uses: cashapp/activate-hermit@v1.1.3
-      - uses: ./.github/actions/build-cache
-      - name: Build Runner Docker Image
-        run: just build-docker runner
-  docker-build-jvm-runners:
-    name: Build JVM Runner Docker Images
-    # if: github.event_name != 'pull_request' || github.event.action == 'enqueued' || contains( github.event.pull_request.labels.*.name, 'run-all')
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-      - uses: cashapp/activate-hermit@v1.1.3
-      - uses: ./.github/actions/build-cache
-      - name: Build JVM Docker Imag
-        run: just build-docker runner-jvm
+      - name: Build Docker Image
+        run: just build-docker ${{ matrix.service }}
   console-e2e:
     name: Console e2e
     # if: github.event_name != 'pull_request' || github.event.action == 'enqueued' || contains( github.event.pull_request.labels.*.name, 'run-all')
@@ -421,4 +389,32 @@ jobs:
             exit 1
           else
             echo "Integration tests passed"
+          fi
+  docker-success:
+    name: Docker Success
+    needs: [docker-build]
+    runs-on: ubuntu-latest
+    if: ${{ always() }}
+    steps:
+      - name: Check docker builds result
+        run: |
+          if [[ "${{ needs.docker-build.result }}" == "failure" ]]; then
+            echo "Docker builds failed"
+            exit 1
+          else
+            echo "Docker builds passed"
+          fi
+  infrastructure-success:
+    name: Infrastructure Success
+    needs: [infrastructure-run]
+    runs-on: ubuntu-latest
+    if: ${{ always() }}
+    steps:
+      - name: Check infrastructure tests result
+        run: |
+          if [[ "${{ needs.infrastructure-run.result }}" == "failure" ]]; then
+            echo "Infrastructure tests failed"
+            exit 1
+          else
+            echo "Infrastructure tests passed"
           fi
